<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true" CodeBehind="PPC_Authorized.aspx.cs" Inherits="HR_Salaries.Pages.PPC.PPC_Authorized" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
      
    <asp:Label ID="lblMessage" runat="server" style=" font-size:x-large;" ></asp:Label>
    <div class="content">
        <div class="container">
            <div class="col-lg-13">
                <div class="sub-content">
                    <div class="list-group">
                        <asp:Panel ID="Panel1" runat="server">


                        <asp:Panel ID="PalChose" runat="server">
                            <div class="row">
                                <div class="col-6 col-md-12" >
                        <asp:Label CssClass="lbl" Width="100%" ID="Label4" runat="server"  Text="المخولين" ></asp:Label>             
                                    </div>
                               </div>
                            </asp:Panel>

                          </asp:Panel>
                        <div dir="rtl">
                         <asp:Panel ID="Panel2" runat="server" Visible="true">


                             <!-- Start Chose for Add or Update-->

                            <div class="row">
    <div class="col-6 col-md-5">
        <asp:Button style="font-size: unset;" ID="ButAdd" runat="server" Text="أضافة" width="100%" CssClass="btn btn-success" OnClick="ButAdd_OnClick"  />
    </div>
    <div class="col-6 col-md-1">
        
    </div>
    <div class="col-6 col-md-1">
        
    </div>    
    <div class="col-6 col-md-5">
        <asp:Button style="font-size: unset;" ID="ButUpdate" runat="server" Text="تعديل" width="100%" CssClass="btn btn-success" OnClick="ButUpdate_OnClick" />
    </div>
    
</div>

                             <!-- End -->

                              <!-- Start Search Panel for add  -->

                             <asp:Panel ID="PalAdd" runat="server" Visible="false">

                              <div class="row">
                              
                              <div class="col-6 col-md-6" ><asp:TextBox ID="txtAdd" class="form-control" runat="server" placeholder="رقم الحساب"></asp:TextBox></div>
                              <div class="col-6 col-md-6" style="text-align: right;">
                                  <asp:Button style="font-size: unset;" ID="btnSerchAdd" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerchAdd_Click"  /> 

                              </div>
                             
                              <div class="col-6 col-md-3"> </div>
                         </div>


                                                        <div class="row" style="padding: 0px 0px 0px 0px;">
                            <div class="col-md-1">  
                                    </div>
                                                            <!--OnSelectedIndexChanged="GVUpdate_PageIndexChanging"-->
                     <div class="col-md-12">  
                     <asp:GridView ID="GridViewAdd" runat="server" BackColor="White" BorderColor="#CCCCCC"
                     BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                     CssClass="table table-striped table-bordered table-condensed"
                     AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                     AutoGenerateSelectButton="True"  AllowSorting="True" OnSelectedIndexChanged="GridViewAdd_SelectedIndexChanged">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
         </div>
                               <div class="col-md-1">  
                                    </div>
   </div>



                            </asp:Panel>
                         
                             


                             <!-- Start Search Panel -->

                              <asp:Panel ID="PalUpdate" runat="server" Visible="false">

                              <div class="row">
                              
                              <div class="col-6 col-md-6" ><asp:TextBox ID="txtUpdate" class="form-control" runat="server" placeholder="رقم الحساب"></asp:TextBox></div>
                              <div class="col-6 col-md-6" style="text-align: right;"><asp:Button style="font-size: unset;" ID="btnSerchUpdate" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerchUpdate_Click"  /> </div>
                            
                              <div class="col-6 col-md-3"> </div>
                         </div>


                                                        <div class="row" style="padding: 0px 0px 0px 0px;">
                            <div class="col-md-1">  
                                    </div>
                                                            <!--OnSelectedIndexChanged="GVUpdate_PageIndexChanging"-->
                     <div class="col-md-12">  
                     <asp:GridView ID="GVUpdate" runat="server" BackColor="White" BorderColor="#CCCCCC"
                     BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                     CssClass="table table-striped table-bordered table-condensed"
                     AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                     AutoGenerateSelectButton="True"  AllowSorting="True" OnSelectedIndexChanged="GVUpdate_SelectedIndexChanged">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
         </div>
                               <div class="col-md-1">  
                                    </div>
   </div>



                            </asp:Panel>


                             <!-- End -->






                             <!-- Start -->

                             


<asp:Panel ID="RowsData" runat="server" Visible="false">


     <div class="row">
    <div class="col-6 col-md-3">
        <asp:Label CssClass="lbl" Width="100%" ID="Label5" runat="server"  Text="Account Number" ForeColor="Red"></asp:Label>
    </div>
    <div class="col-6 col-md-3">
        <asp:TextBox CssClass="txt" Width="100%" ID="Account_No" runat="server"  Text="" TabIndex="1" Enabled="false"></asp:TextBox>
    </div>
   </div>




 <div class="row">
    <div class="col-6 col-md-3">
        <asp:Label CssClass="lbl" Width="100%" ID="Label12" runat="server"  Text="Authorized_Name" ForeColor="Red"></asp:Label>
    </div>
    <div class="col-6 col-md-3">
        <asp:TextBox CssClass="txt" Width="100%" ID="Authorized_Name" runat="server"  Text="" required TabIndex="1"></asp:TextBox>
    </div>
    <div class="col-6 col-md-3">
        <asp:Label CssClass="lbl" Width="100%" ID="Label2" runat="server"  Text="Authorized_Address" ForeColor="Red"></asp:Label>
    </div>
    <div class="col-6 col-md-3">
        <asp:TextBox CssClass="txt" Width="100%" ID="Authorized_Address" runat="server"  Text="" required TabIndex="1" Enabled="true"></asp:TextBox>    </div>    </div>
 <div class="row">
    <div class="col-6 col-md-3">
        <asp:Label CssClass="lbl" Width="100%" ID="Label1" runat="server"  Text="Authorization_profession" ForeColor="Red"></asp:Label>
    </div>
    <div class="col-6 col-md-3">
        <asp:TextBox CssClass="txt" Width="100%" ID="Authorization_profession" runat="server"  Text="" required TabIndex="1" Enabled="true"></asp:TextBox>
    </div>
    <div class="col-6 col-md-3">
        <asp:Label CssClass="lbl" Width="100%" ID="Label3" runat="server"  Text="Authorization_mobile" ForeColor="Red"></asp:Label>
    </div>
    <div class="col-6 col-md-3">
        <asp:TextBox CssClass="txt" Width="100%" ID="Authorization_mobile" runat="server"  Text="" required TabIndex="1" Enabled="true"></asp:TextBox>  
         
    </div>    </div>
    </asp:Panel>



                             <!-- End -->

                           
                       </asp:Panel>
                                </div>
                        <!-- OnClick -->
                        <br />


                            <div class="col-6 col-md-12">
                                <asp:Button style="font-size: unset;" ID="btnSend" runat="server" Text="تنفيذ" width="100%" CssClass="btn btn-success" OnClick="btnSend_Click" Visible="false" />
                            </div>    
                         <br />
                         
                        <div class="col-6 col-md-12">
                                <asp:Button style="font-size: unset;" ID="btnCancel" runat="server" Text="ألغـــاء" width="100%" CssClass="btn btn-danger" OnClick="btnCancel_Click" Visible="false" />
                            </div>   
                            <div class="col-6 col-md-3">
                                <asp:Label ID="AddUpdate" runat="server" Text="Label111" Visible="false"></asp:Label>
                                <asp:Label ID="idUpdate" runat="server" Text="" Visible="false"></asp:Label>
                            </div>
                            </div>
                            
                         </div>
                     </div>
                 </div>
             </div>
        
    

  
</asp:Content>
